name: Docker Image CI/CD to deploy on azure web app

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  DOCKER_IMAGE_NAME: 'myweatherapp-docker-action'
  AZURE_WEB_APP: 'weather-web-app-backend'
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Write DB url
      uses: christian-draeger/write-properties@1.0.1
      with:
        path: '**/application-prod.properties'
        property: 'spring.datasource.url'
        value: ${{secrets.AZURE_DB_URL}}
    - name: Write DB USERNAME
      uses: christian-draeger/write-properties@1.0.1
      with:
        path: './src/main/resources/application-prod.properties'
        property: 'spring.datasource.username'
        value: ${{secrets.AZURE_DB_USERNAME}}  
    - name: Write DB PASSWORD
      uses: christian-draeger/write-properties@1.0.1
      with:
        path: './src/main/resources/application-prod.properties'
        property: 'spring.datasource.password'
        value: ${{secrets.AZURE_DB_PASSWORD}} 
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{env.DOCKER_IMAGE_NAME}}:latest
    - name: Docker Login
      run: docker login --username '${{secrets.DOCKER_LOGIN}}' --password '${{secrets.DOCKER_PASSWORD}}'
    - name: Tag image
      run: docker tag '${{env.DOCKER_IMAGE_NAME}}':latest '${{secrets.DOCKER_LOGIN}}'/'${{env.DOCKER_IMAGE_NAME}}':latest
    - name: Push the Docker image to docker hub
      run: docker push '${{secrets.DOCKER_LOGIN}}'/'${{env.DOCKER_IMAGE_NAME}}':latest

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

    - name: Azure WebApp deploymnet
      uses: Azure/webapps-deploy@v2
      with:
        app-name: '${{env.AZURE_WEB_APP}}'
        images: '${{secrets.DOCKER_LOGIN}}/${{env.DOCKER_IMAGE_NAME}}:latest'
